services:
  - type: web
    name: kiosk-whatsapp
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        value: whatsapp:+14155238886
      - key: PORT
        value: 10000

