// Traducciones para el servidor de email
const translations = {
  es: {
    title: 'Ticket de Estacionamiento',
    plate: 'Matrícula',
    zone: 'Zona',
    start: 'Inicio',
    end: 'Fin',
    duration: 'Duración',
    payment: 'Pago',
    amount: 'Importe',
    thanks: 'Gracias por su compra.',
    generatedBy: 'Este ticket ha sido generado automáticamente por el sistema de gestión de aparcamiento Meypark.',
    qrDescription: 'Escanea este código QR para verificar el ticket',
    zoneCoche: 'Zona Coche',
    zoneMoto: 'Zona Moto',
    zoneCamion: 'Zona Camión',
    zoneGreen: 'Zona Verde',
    zoneBlue: 'Zona Azul'
  },
  ca: {
    title: 'Tiquet d\'Aparcament',
    plate: 'Matrícula',
    zone: 'Zona',
    start: 'Inici',
    end: 'Fi',
    duration: 'Durada',
    payment: 'Pagament',
    amount: 'Import',
    thanks: 'Gràcies per la seva compra.',
    generatedBy: 'Aquest tiquet ha estat generat automàticament pel sistema de gestió d\'aparcament Meypark.',
    qrDescription: 'Escaneja aquest codi QR per verificar el tiquet',
    zoneCoche: 'Zona Cotxe',
    zoneMoto: 'Zona Moto',
    zoneCamion: 'Zona Camió',
    zoneGreen: 'Zona Verda',
    zoneBlue: 'Zona Blava'
  },
  en: {
    title: 'Parking Ticket',
    plate: 'Plate',
    zone: 'Zone',
    start: 'Start',
    end: 'End',
    duration: 'Duration',
    payment: 'Payment',
    amount: 'Amount',
    thanks: 'Thank you for your purchase.',
    generatedBy: 'This ticket has been automatically generated by the Meypark parking management system.',
    qrDescription: 'Scan this QR code to verify the ticket',
    zoneCoche: 'Car Zone',
    zoneMoto: 'Motorcycle Zone',
    zoneCamion: 'Truck Zone',
    zoneGreen: 'Green Zone',
    zoneBlue: 'Blue Zone'
  }
};

function getTranslations(locale) {
  return translations[locale] || translations.es;
}

function formatDateTime(date) {
  return date.toLocaleString('es-ES', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Europe/Madrid'
  });
}

module.exports = {
  translations,
  getTranslations,
  formatDateTime
};
