// Traducciones y funciones de formateo para el servidor de email

// Función para formatear fecha y hora en formato 24h con zona horaria de España
const formatDateTime = (date, locale = 'es') => {
  const d = new Date(date);
  
  // Ajustar a zona horaria de España (UTC+1 en invierno, UTC+2 en verano)
  // España está en UTC+1, pero necesitamos verificar si es horario de verano
  const spainOffset = 1; // UTC+1 (España)
  const utc = d.getTime() + (d.getTimezoneOffset() * 60000);
  const spainTime = new Date(utc + (spainOffset * 3600000));
  
  // Formato 24h: DD/MM/YYYY HH:mm
  const day = String(spainTime.getDate()).padStart(2, '0');
  const month = String(spainTime.getMonth() + 1).padStart(2, '0');
  const year = spainTime.getFullYear();
  const hours = String(spainTime.getHours()).padStart(2, '0');
  const minutes = String(spainTime.getMinutes()).padStart(2, '0');
  
  return `${day}/${month}/${year} ${hours}:${minutes}`;
};

// Función para formatear duración
const formatDuration = (start, end, locale = 'es') => {
  const startTime = new Date(start);
  const endTime = new Date(end);
  const diffMs = endTime - startTime;
  const diffMinutes = Math.floor(diffMs / (1000 * 60));
  const hours = Math.floor(diffMinutes / 60);
  const minutes = diffMinutes % 60;
  
  if (hours > 0) {
    return `${hours}h ${minutes}min`;
  } else {
    return `${minutes}min`;
  }
};

// Función para obtener el año actual dinámicamente
const getCurrentYear = () => {
  return new Date().getFullYear();
};

// Traducciones multiidioma
const getTranslations = (locale = 'es') => {
  const currentYear = getCurrentYear(); // ✅ AÑO DINÁMICO
  
  const translations = {
    es: {
      subject: 'Meypark',
      subtitle: 'Smart Parking Management System',
      greeting: 'Estimado cliente,',
      intro: 'Hemos procesado exitosamente su pago de estacionamiento. A continuación encontrará los detalles de su ticket:',
      title: 'Ticket de Estacionamiento',
      ticketDetails: 'Detalles del Ticket',
      plate: 'Matrícula',
      zone: 'Zona',
      zoneGreen: 'Zona Verde',
      zoneBlue: 'Zona Azul',
      zonePlaya: 'Zona Coche',
      zoneCosta: 'Zona Moto',
      zoneParque: 'Zona Camión',
      startTime: 'Hora de inicio',
      endTime: 'Hora de finalización',
      duration: 'Duración',
      totalPrice: 'Precio total',
      paymentMethod: 'Método de pago',
      card: 'Tarjeta',
      qr: 'QR Pay',
      mobile: 'Apple/Google Pay',
      cash: 'Efectivo',
      bizum: 'Bizum',
      thanks: 'Gracias por elegir Meypark',
      footer: 'Este ticket ha sido generado automáticamente por el sistema de gestión de aparcamiento Meypark.',
      copyright: `© ${currentYear} Meypark`, // ✅ AÑO DINÁMICO
      generated: 'Generado automáticamente por Meypark',
      sent: 'Enviado el'
    },
    ca: {
      subject: 'Meypark',
      subtitle: 'Sistema de Gestió d\'Aparcament Intel·ligent',
      greeting: 'Estimat client,',
      intro: 'Hem processat amb èxit el seu pagament d\'estacionament. A continuació trobarà els detalls del seu tiquet:',
      title: 'Tiquet d\'Estacionament',
      ticketDetails: 'Detalls del Tiquet',
      plate: 'Matrícula',
      zone: 'Zona',
      zoneGreen: 'Zona Verda',
      zoneBlue: 'Zona Blava',
      zonePlaya: 'Zona Cotxe',
      zoneCosta: 'Zona Moto',
      zoneParque: 'Zona Camió',
      startTime: 'Hora d\'inici',
      endTime: 'Hora de finalització',
      duration: 'Durada',
      totalPrice: 'Preu total',
      paymentMethod: 'Mètode de pagament',
      card: 'Targeta',
      qr: 'QR Pay',
      mobile: 'Apple/Google Pay',
      cash: 'Efectiu',
      bizum: 'Bizum',
      thanks: 'Gràcies per triar Meypark',
      footer: 'Aquest tiquet ha estat generat automàticament pel sistema de gestió d\'aparcament Meypark.',
      copyright: `© ${currentYear} Meypark`, // ✅ AÑO DINÁMICO
      generated: 'Generat automàticament per Meypark',
      sent: 'Enviat el'
    },
    en: {
      subject: 'Meypark',
      subtitle: 'Smart Parking Management System',
      greeting: 'Dear customer,',
      intro: 'We have successfully processed your parking payment. Below you will find the details of your ticket:',
      title: 'Parking Ticket',
      ticketDetails: 'Ticket Details',
      plate: 'Plate',
      zone: 'Zone',
      zoneGreen: 'Green Zone',
      zoneBlue: 'Blue Zone',
      zonePlaya: 'Car Zone',
      zoneCosta: 'Motorcycle Zone',
      zoneParque: 'Truck Zone',
      startTime: 'Start time',
      endTime: 'End time',
      duration: 'Duration',
      totalPrice: 'Total price',
      paymentMethod: 'Payment method',
      card: 'Card',
      qr: 'QR Pay',
      mobile: 'Apple/Google Pay',
      cash: 'Cash',
      bizum: 'Bizum',
      thanks: 'Thank you for choosing Meypark',
      footer: 'This ticket has been automatically generated by the Meypark parking management system.',
      copyright: `© ${currentYear} Meypark`, // ✅ AÑO DINÁMICO
      generated: 'Automatically generated by Meypark',
      sent: 'Sent on'
    }
  };
  
  return translations[locale] || translations.es;
};

module.exports = { getTranslations, formatDateTime, formatDuration };