// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web; // Usar configuración web para Linux
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_qzohm27gNO_BVQxD0a0rN5cvQrZkSaw',
    appId: '1:480696506917:web:abbbdc813f96774217bdcc',
    messagingSenderId: '480696506917',
    projectId: 'optima-360-b055b',
    authDomain: 'optima-360-b055b.firebaseapp.com',
    storageBucket: 'optima-360-b055b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11HPf-ukpAo3D6XOLmiQOM1YGweuG8Vw',
    appId: '1:480696506917:android:90e769f26c15178e17bdcc',
    messagingSenderId: '480696506917',
    projectId: 'optima-360-b055b',
    storageBucket: 'optima-360-b055b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDISPMoeEu1uqycKjIQdcToT-IaXd0EceM',
    appId: '1:480696506917:ios:7b39458e7fa07afe17bdcc',
    messagingSenderId: '480696506917',
    projectId: 'optima-360-b055b',
    storageBucket: 'optima-360-b055b.firebasestorage.app',
    iosBundleId: 'com.example.kioskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDISPMoeEu1uqycKjIQdcToT-IaXd0EceM',
    appId: '1:480696506917:ios:7b39458e7fa07afe17bdcc',
    messagingSenderId: '480696506917',
    projectId: 'optima-360-b055b',
    storageBucket: 'optima-360-b055b.firebasestorage.app',
    iosBundleId: 'com.example.kioskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_qzohm27gNO_BVQxD0a0rN5cvQrZkSaw',
    appId: '1:480696506917:web:abbbdc813f96774217bdcc',
    messagingSenderId: '480696506917',
    projectId: 'optima-360-b055b',
    authDomain: 'optima-360-b055b.firebaseapp.com',
    storageBucket: 'optima-360-b055b.firebasestorage.app',
  );
}
